# Generated by Django 2.1.1 on 2020-03-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
