# Generated by Django 2.1.1 on 2020-03-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0003_userdetail_base64image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='base64image',
            field=models.CharField(default='', max_length=5000000000),
        ),
    ]
