# Generated by Django 2.1.1 on 2020-03-26 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiServer', '0004_auto_20200324_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAttendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default='', max_length=50)),
                ('no_of_classes_taken', models.IntegerField(default=0)),
                ('no_of_classes_attended', models.IntegerField(default=0)),
                ('user_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
